### ISSUE TITLE
Unsupported project type manuscript

### ISSUE THREAD

**Issue by jesuscapistran** [cwickham/manuscript-template-vscode#2]
## Error 

![jesuscapistran 2023-09-24 at 16 33 18](https://github.com/cwickham/manuscript-template-vscode/assets/45544457/14deb515-63b9-469f-9976-3ee1cb6f1dd0)

## Solution: Change the title of the project in _quarto.yml  

```
project:
  title: "Manuscript"
execute:
  freeze: auto
format:
  html:
    toc: true
    comments:
      hypothesis: true
```
